mopa_barcode_display:
    pattern:   /mopa/barcode/send/{type}/{enctext}
    defaults:  { _controller: MopaBarcodeBundle:Barcode:displayBarcode }
    requirements:
        enctext: ".+"

mopa_barcode_download:
    pattern:   /mopa/barcode/download/{type}/{level}/{size}/{margin}/{useOverlay}/{enctext}
    defaults:  { _controller: MopaBarcodeBundle:Barcode:downloadBarcode }
    requirements:
        enctext: ".+"
